import { file } from 'bun'
const templates = await file('src/html/templates.html').text()

const templateRegexp = /<template\s+id="([^"]+)">([\s\S]*?)<\/template>/g
const placeholderRegexp = /%\{([^}]+)\}/g
const placehodlerExcludingType = /%\{([^:}]+)(?::[^}]*)?\}/g

const matches = [...templates.matchAll(templateRegexp)]
// We discard the template tags and keep the id for naming.
const functions = matches.map(([_, id, content]) => {
	if(!(id && content)) {
		throw new Error('match for template was malformed')
	}

	// We're converting template id from kebab-case to camelCase.
	const name = 'make' + id.split('-').map((part) => {
		return part[0]!.toUpperCase() + part.slice(1)
	}).join('')

	const variables = new Map<string, string>()
	for (const [_, placeholder] of content.matchAll(placeholderRegexp)) {
		if(!placeholder) {throw new Error(
			'Undefined placeholder in content. This should never happen'
		)}
		const typeSeparatorPos = placeholder.indexOf(':')
		let key = placeholder
		let type = 'string'
		if(typeSeparatorPos !== -1) {
			key = placeholder.slice(0, typeSeparatorPos).trim()
			type = placeholder.slice(typeSeparatorPos + 1).trim()
		}
		if(!variables.has(key) || variables.get(key) === 'unknown') {
			variables.set(key, type)
		}
	}

	const params: string[] = [...variables.entries()].map(
		([key, type]) => `${key}: ${type}`
	)
	const replaceString = params.length > 1 ? '${p.$1}' : '${$1}'
	const body = content.trim()
		.replaceAll(placehodlerExcludingType, replaceString)
		.replaceAll('`', '\\`')
	const signature = `export function ${name}(`
	const returnType = '): string {'
	let paramString = ''
	if(params.length > 0) {
		paramString = `${params.join(', ')}`
		if(params.length > 1) {
			paramString =`p:{${params.join(', ')}}`
		}
	}
	if(params.length > 1 &&	(signature + paramString + returnType).length > 80) {
		paramString = `p: {\n\t${params.join(',\n\t')}\n}`
	}
	return(
		`${signature}${paramString}${returnType}\n` +
			`\treturn html\`${body}\`\n` +
		`}`
	)
})

await Bun.write('gen/HTMLtemplates.ts',
	'// GENERATED BY buildHTMLtemplates.ts\n' +
	'// We tag the literals with html for syntax highlighting in most editors.\n' +
	'const html = String.raw\n\n' +
	functions.join('\n\n')
)
