import type { SQL } from "bun"

interface Column {
	column_name: string,
	column_type: string,
	data_type: string,
	is_nullable: 'YES'|'NO'
}

const mariadbTypeMap: Record<string, string> = {
	tinyint: 'number', smallint: 'number', mediumint: 'number', int: 'number',
	// remember to toggle bigint option in bun.
	bigint: 'number|bigint',
	float: 'number', double: 'number',
	decimal: 'string', "bit(1)": 'boolean',
	char: 'string', binary: 'string', varchar: 'string', varbinary: 'string',
	tinyblob: 'string', tinytext: 'string', blob: 'string', text: 'string',
	mediumblob: 'string', mediumtext: 'string',
	longblob: 'string', longtext: 'string',
	inet4: 'string', inet6: 'string', uuid: 'string',
	set: 'string', xmltype: 'string',
	date: 'Date', datetime: 'Date', timestamp: 'Date',
	time: 'number', year: 'number'
}

export default async function generateTableInterfaces(
	sql: SQL, ...tableNames: string[]
) {
	console.log('Generating typescript interfaces for tables...')
	const interfaces: string[] = []
	for(const table of tableNames) {
		interfaces.push(await generateInterface(sql, table))
	}
	await Bun.write(
		'gen/dbTableInterfaces.ts',
		'// GENERATED BY generateTableInterfaces.ts\n' + interfaces.join('\n\n')
	)
}

async function generateInterface(
	sql: SQL, tableName: string
): Promise<string> {
	const columns: Column[] = await sql`
		SELECT column_name, column_type, data_type, is_nullable
		FROM information_schema.columns
		WHERE table_schema = DATABASE() AND table_name = ${tableName}
		ORDER BY ordinal_position;
	`
	if(columns.length === 0) {
		throw new Error(`No columns found for ${tableName} - Does it exist?`)
	}
	const props = columns.map(
		col => `\t${col.column_name}: ${tsType(col)}`
	).join(',\n')
	return `export interface ${toPascalCase(tableName)} {\n${props}\n}`
}



function tsType(col: Column): string {
	const enumMatch = col.column_type.match(/^enum\((.+)\)$/i)
	if(enumMatch) {
		return enumMatch[1]!.split(',').map(s => s.trim()).join('|')
	}
	else {
		const baseType = mariadbTypeMap[col.data_type] ?? 'unknown'
		return col.is_nullable === 'YES' ? `${baseType}|null` : baseType
	}
}

function toPascalCase(name:string): string {
	return name.split(/[_-]/).map(
		s => s.charAt(0).toUpperCase() + s.slice(1)
	).join('')
}