CREATE DATABASE IF NOT EXISTS riftbound;
USE riftbound;

CREATE TABLE IF NOT EXISTS metadata (
	id TINYINT UNSIGNED PRIMARY KEY DEFAULT 1,
	schema_version INT UNSIGNED NOT NULL,
	last_synced_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	content_version VARCHAR(32) NOT NULL,
	content_last_updated_at VARCHAR(32) NOT NULL,
	CONSTRAINT single_row CHECK (id = 1)
);

CREATE TABLE IF NOT EXISTS types (
	id TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	sort_order TINYINT UNSIGNED UNIQUE,
	name VARCHAR(32) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS rarities (
	id TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	sort_order TINYINT UNSIGNED UNIQUE,
	name VARCHAR(32) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS domains (
	id TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	sort_order TINYINT UNSIGNED UNIQUE,
	name VARCHAR(32) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS sets (
	id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	code VARCHAR(8) UNIQUE NOT NULL,
	name VARCHAR(255) UNIQUE NOT NULL,
	cardmarket_id BIGINT UNIQUE,
	release_date DATE,
	card_count_denominator SMALLINT UNSIGNED,
	card_count_total SMALLINT UNSIGNED
);

CREATE TABLE IF NOT EXISTS artists (
	id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(255) UNIQUE NOT NULL,
	website VARCHAR(255) UNIQUE DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS cards (
	id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	riot_id VARCHAR(255) UNIQUE NOT NULL,
	collector_number BIGINT UNIQUE NOT NULL,
	name VARCHAR(255) UNIQUE NOT NULL,
	type_id TINYINT UNSIGNED NOT NULL,
	FOREIGN KEY(type_id) REFERENCES types(id),
	domain_id TINYINT UNSIGNED NOT NULL,
	FOREIGN KEY(domain_id) REFERENCES domains(id),
	rarity_id TINYINT UNSIGNED NOT NULL,
	FOREIGN KEY(rarity_id) REFERENCES rarities(id),
	artist_id INT UNSIGNED NOT NULL,
	FOREIGN KEY(artist_id) REFERENCES artists(id),
	set_id INT UNSIGNED NOT NULL,
	FOREIGN KEY(set_id) REFERENCES sets(id),
	energy TINYINT NOT NULL,
	might TINYINT NOT NULL,
	cost TINYINT NOT NULL,
	power TINYINT NOT NULL,
	cardmarket_id BIGINT UNSIGNED UNIQUE,
	img VARCHAR(255) UNIQUE,
	thumbnail VARCHAR(255) UNIQUE,
	description VARCHAR(1000),
	flavor_text VARCHAR(1000)
);

CREATE TABLE IF NOT EXISTS tags (
	id SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(32) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS card_tags (
	card_id INT UNSIGNED NOT NULL,
	FOREIGN KEY (card_id) REFERENCES cards(id),
	tag_id SMALLINT UNSIGNED NOT NULL,
	FOREIGN KEY (tag_id) REFERENCES tags(id),
	PRIMARY KEY(card_id, tag_id)
);

CREATE TABLE IF NOT EXISTS keywords (
	id SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(32) UNIQUE NOT NULL,
	rules_entry VARCHAR(32) UNIQUE,
	formatting VARCHAR(32) UNIQUE,
	color VARCHAR(8),
	rules_description VARCHAR(255),
	card_description VARCHAR(255),
);

CREATE TABLE IF NOT EXISTS card_keywords (
	card_id INT UNSIGNED NOT NULL,
	FOREIGN KEY(card_id) REFERENCES cards(id),
	keyword_id SMALLINT UNSIGNED NOT NULL,
	FOREIGN KEY(keyword_id) REFERENCES keywords(id),
	PRIMARY KEY(card_id, keyword_id)
);